### ISSUE TITLE
Image files are incomplete or cannot be viewed

### ISSUE THREAD

**Issue by Bondedrobin** [ROGsamurai/Djipis-Ocarina-of-Time-3DS-Experience#2]
Each individual texture file in this repository seems to not be viewable. Is your intent to not distribute the PNG files you've worked on and to only provide this repository as a sort of file tree/list of reworked textures? Or am I viewing these files incorrectly?

I ask because my intention it to explore this texture back and repack it into an OTR via Retro for personal use as practice with SoH modding.

**Comment by ROGsamurai** [comment]
I only combined the otrs because I have ocd lmao and dont like to see alot of clutter. The repository is infact just a tree/list to keep the files in the folders they need to be in. The original mod is located here [ORIGINAL](https://gamebanana.com/mods/477979)

You would need to use a combination of retro and mpq editor to make edits. Retro will not extract HD.png's only the original file sizes. So you would need Djipi's original files that he has personally to change them.

[RETRO Download](https://github.com/HarbourMasters/retro/releases/tag/0.0.5-alpha.2)

[MPQ Editor Download](https://www.hiveworkshop.com/threads/ladiks-mpq-editor.249562/)

more information can be found on how to edit these files in the Harbour Master Discord [HERE](https://discord.gg/shipofharkinian)

**Comment by Bondedrobin** [comment]
So what I'm gathering is there isn't actually a repository of all the HD PNGs and I can't edit them because Djipi did not distribute them?

**Comment by ROGsamurai** [comment]
correct, only some pngs will show and be editable unless you know what your looking for. Djipi doesnt support modding his textures.

Some will look like this
![2](https://github.com/ROGsamurai/Djipis-Ocarina-of-Time-3DS-Experience/assets/94874077/bc3b1c5a-c28d-474d-8a51-823bb4e9fed0)

and some will look like this
![Untitled](https://github.com/ROGsamurai/Djipis-Ocarina-of-Time-3DS-Experience/assets/94874077/80a23f26-d277-4370-8614-7569584320d7)
